# Site settings
title: "Home"
description: >-
  (c) 2025 Nico Marr.
baseurl: ""
url: ""
github_username:  nicomarr

# Build settings
theme: minima
# plugins:
#   - jekyll-feed

header_pages:
  - tutorials.md
  - publications.md
  - tools.md
  - services.md
  - about.md

include:
  - _data/articles-metadata.csv
  - _data/update-log.json
  - .mp4
  
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/