# Site settings
title: "Home"
description: >-
  (c) 2025 Nico Marr.
baseurl: ""
url: "https://nicomarr.github.io"
github_username:  nicomarr

# Build settings
theme: minima
# plugins:
#   - jekyll-feed

header_pages:
  - publications.md
  - tools.md
  - teaching.md
  - tutorials.md
  - about.md
  - contact.md

# Default settings for pages
defaults:
  - scope:
      path: "thanks.md"
    values:
      sitemap: false

include:
  - _data/articles-metadata.csv
  - _data/update-log.json
  - .mp4
  
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/